### ISSUE TITLE
Issue updating

### ISSUE THREAD

**Issue by Filoz** [hackzilla/TicketBundle#101]
Hi @hackzilla , 
I tried to update to the latest version (3.0@dev) but I got this error:

`  Mapping "ticket_message_attachment" does not exist. The configuration for the class "Hackzilla\Bundle\TicketBundle\Entity\TicketMessageWithAttachment" is probably incorrect as   the mapping to use for the field "attachmentFile" could not be found.`

I didn't change nothing in my code.... this is my configuration:

```
hackzilla_ticket:
    user_class:             UserBundle\Entity\User
    ticket_class:           Hackzilla\Bundle\TicketBundle\Entity\Ticket
    message_class:          Hackzilla\Bundle\TicketBundle\Entity\TicketMessage

```

There is something I need to change to try the 3.0 version?

Thank you

**Comment by hackzilla** [comment]
This is related to me making attachments for tickets, but trying to make them optional.

([more info](https://github.com/hackzilla/TicketBundle/blob/develop/Resources/doc/setup/feature/attachments.md))

Though it sounds like I didn't succeed at making them optional.
I will have a look this evening.

**Comment by hackzilla** [comment]
I've figured out what is causing it.

The uploader is looking for the config ```ticket_message_attachment``` to be defined.
I need to only load this if the feature is enabled.

If you add this config, then it should work again.

```
# app/config/config.yml
vich_uploader:
    db_driver: orm

    mappings:
        ticket_message_attachment:
            uri_prefix:         /attachment
            upload_destination: %kernel.root_dir%/../var/uploads/attachment/
```

**Comment by hackzilla** [comment]
```
class AppKernel extends Kernel
{
    public function registerBundles()
    {
        $bundles = array(
//            new Vich\UploaderBundle\VichUploaderBundle(),
        );
    }
```
If you enable ```VichUploaderBundle``` then the above config needs to be added into ```config.yml```
