### ISSUE TITLE
How can i to implement class - methods?

### ISSUE THREAD

**Issue by ruben2016** [hackzilla/TicketBundle#103]
Hi,

I am implementing the bundle in Symfony 3, with general installation but I do not know how to put this:
<?php
namespace AppBundle\Entity;
class User implements \Hackzilla\Bundle\TicketBundle\Model\UserInterface
{
}

Can you help me?

Thanks.

**Comment by hackzilla** [comment]
Hey, 

The Bundle has built in entity that you can use, or copy.

```https://github.com/hackzilla/TicketBundle/tree/master/Entity```

Also checkout the [Ticket Bundle Demo App](https://github.com/hackzilla/TicketBundleDemoApp/blob/master/app/config/config.yml]) to config, as I've commented out how you specify them.
