### ISSUE TITLE
How to change the roles of Hackzilla

### ISSUE THREAD

**Issue by ruben2016** [hackzilla/TicketBundle#104]
Hi,

We use an application with different roles, not Fosuserbundle. We have admin, user ... Because with Fosuserbundle works well, but with our roles gives us FORBIDDEN.

Is it possible to change the code Hackzilla?

How could we change roles?

Thank you

**Comment by hackzilla** [comment]
This bundle shouldn't be tied to FOS User Bundle, as I did some work in #94 
However you will need to add the role ```ROLE_TICKET_ADMIN``` to the user.

Can you give me any idea what you use instead of FOS User Bundle, as I wanted to write some additional tests

**Comment by hackzilla** [comment]
V4 will allow you to change the ticket admin role from ```ROLE_TICKET_ADMIN``` (not yet released)
