### ISSUE TITLE
Unable to find twig base template from HackzillaTicketBundle::layout.html.twig

### ISSUE THREAD

**Issue by nicolas-san** [hackzilla/TicketBundle#105]
Hi, 
and first thanks for your work, I'm really happy to try this bundle, and not to have to use external software !

But, I have an issue, I have updated my symfony to 2.8, and install the bundle, following the doc:
`composer require hackzilla/ticket-bundle`

When I try to rich the ticket bundle page, I have this error:

> Unable to find template "::base.html.twig" (looked into: /var/www/folder/subfolder/site/vendor/symfony/symfony/src/Symfony/Bridge/Twig/Resources/views/Form) in HackzillaTicketBundle::layout.html.twig at line 1.

I use bootstrap3 form, and I have configured twig like this:
```
twig:
    [...]
    form:
        resources: ['bootstrap_3_layout.html.twig']
```

When I see the layout file:
https://github.com/hackzilla/TicketBundle/blob/develop/Resources/views/layout.html.twig
```

{% extends '::base.html.twig' %}

{% block body %}
    {% block hackzilla_ticket_content %}{% endblock %}
{% endblock body %}
```

But in my twig directory: 
![ticketbundletwigissue](https://cloud.githubusercontent.com/assets/7702787/25893298/86c75a44-3577-11e7-8d3b-a8053f05bfe3.png)
I do not have base.html.twig file

Am I missing something ?

SOLUTION: you need to have a base.html.twig in the app/Resources/views/ thanks to @bubnov-mikhail

**Comment by bubnov-mikhail** [comment]
You are missing app/Resources/views/base.html.twig

**Comment by nicolas-san** [comment]
ok, make sense :)
I can see it here: https://github.com/hackzilla/TicketBundleDemoApp/tree/master/app/Resources/views

But, I don't see it in the doc, I have to take it from the demo app or another way ?
Why I don't have this file ? My fault or install issue ?

**Comment by bubnov-mikhail** [comment]
Usually you have it )
So just add/copy/create this file

**Comment by nicolas-san** [comment]
Ok, understood ! It is my base template, but I dont have it.
I have started my project some times ago, and I have all my tpl files in my bundles, a file_exist check could be a good idea.

Thanks for the quick and effective help !

**Comment by hackzilla** [comment]
The demo was based on the Symfony-Standard project, and there is were the file ::base.html.twig came from.

**Comment by hackzilla** [comment]
If you don't want to create that file, then override layout.html.twig.

**Comment by nicolas-san** [comment]
Ok, I will do that, but in my usecase, with an old symfony install the file is not necessary here by default

Thanks for your reply, I close :)
