### ISSUE TITLE
reserved word in column name 'status'

### ISSUE THREAD

**Issue by nicolas-san** [hackzilla/TicketBundle#108]
Hi @hackzilla and everyone :)

When I look the code, I see in the doctrine mapping column name 'status':
[TicketMessageWithAttachment.orm.xml](https://github.com/hackzilla/TicketBundle/blob/develop/Resources/config/doctrine/model/attachment/TicketMessageWithAttachment.orm.xml)
[TicketMessage.orm.xml](https://github.com/hackzilla/TicketBundle/blob/develop/Resources/config/doctrine/model/plain/TicketMessage.orm.xml)

According to this page, it's a reserved keyword, if it's quoted, it's fine:
[mysql reserved keywords](https://dev.mysql.com/doc/refman/5.5/en/keywords.html)
[mysql identifiers](https://dev.mysql.com/doc/refman/5.5/en/identifiers.html)

But, in my case, symfony 2.8, with doctrine, when I look at the debug toolbar, and select "runnable query" the column names are not quoted.

An issue raised and closed about that:
[issue about reserved keywords](https://github.com/doctrine/doctrine2/issues/2409)

And to finish the doctrine doc page about it, you need to quote the column name yourself:
[doctrine quoting-reserved-words](http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/basic-mapping.html#quoting-reserved-words)

What about renaming columns 'status' and 'user' ?

**Comment by hackzilla** [comment]
This make sense, however I wouldn't want to do it without bumping to a major version.

**Comment by nicolas-san** [comment]
In the waiting, perhaps just add the quote ` the the xml files would avoid potential trouble, without breaking compatibility

**Comment by hackzilla** [comment]
If it doesn't break anything, then I'm open to doing that.
