### ISSUE TITLE
Extracting TicketManager into seperate Library

### ISSUE THREAD

**Issue by hackzilla** [hackzilla/TicketBundle#109]
I thinking extracting TicketManager and various interfaces into a ticket message library.
This will allow TicketManager improvements to benefit all versions of the Ticket Bundle.

Thoughts?

**Comment by nicolas-san** [comment]
Can you be more specific ? 
You want extract TicketManager from what ?
I have difficulties to picture what you want to do :)

**Comment by hackzilla** [comment]
I mean to pull out the implementation (Interface, services), leaving the symfony specific bits (Form Type, Templates) in the bundle.

The idea being, if you needed to create tickets via email, then you would need all the symfony dependancies.

Maybe even create a Zend implementation using the core ticket library.

The idea is pretty similar to what I've done with my Password Generator and Bundle.

* https://github.com/hackzilla/password-generator
* https://github.com/hackzilla/password-generator-bundle

**Comment by nicolas-san** [comment]
Ok, could be good to add the ticket functionality to any php project.
In my case, I found this bundle searching for a symfony helpdesk, and I can't tell if it will be usefull to others :)
