### ISSUE TITLE
I have to allow status modification without a message

### ISSUE THREAD

**Issue by nicolas-san** [hackzilla/TicketBundle#111]
First, my opinion is, we have to add a message to change the status, because it's good for customer relationship, but I am not the one using the helpdesk and I need to allow this.

In the trait, we have:
```
    /**
     * @var string
     *
     * @Assert\NotBlank()
     */
    protected $message;
```
The ideal is to add a configuration option to allow or not this field to be empty, but, I can't search for this now.
Have you an idea ? (I hope I miss something simple :) )

**Comment by hackzilla** [comment]
If you need to customise the traits, the easiest way would to implement the interface directly.

Hackzilla\Bundle\TicketBundle\Model\TicketMessageInterface

Then you can manually copy and paste the contents of the trait, and make changes.

**Comment by nicolas-san** [comment]
I am sorry, but I have difficulties to picture what you say, I understand the principle, but I am not seeing how to use is in my case

**Comment by nicolas-san** [comment]
in the doc 
 
> Use the **TicketBundle xml** as a basis and copy it into your bundle.
The link is dead

**Comment by hackzilla** [comment]
Whoops.

https://github.com/hackzilla/TicketBundle/tree/develop/Resources/config/doctrine/model

**Comment by nicolas-san** [comment]
I think I miss something ...

`Class "myapp\Entity\TicketMessageWithAttachmentFromMail" is not a valid entity or mapped super class.`

Btw a question, is it logical to have $message assert notNull in the trait, but null=true in the doctrine xml definition, and required%false in the form type ?

**Comment by hackzilla** [comment]
probably not logical.
but at least nothing appears to be breaking.

**Comment by nicolas-san** [comment]
Yes :) it is working, my point is perhaps it is better to not assert notNull in the entity, and let users override this with custom entities, or custom tpl (if the validation of the form is enough)

At first, my goal was to add a configuration variable to allow empty messages or not, and not send notification if the message is empty, but with the assert, I can't find a good way to do it

**Comment by hackzilla** [comment]
My hope was that developers would roll their own entities.

I'm trying to remove doctrine and symfony as a dependancy, at least for the core.
Then people can decide to use between doctrine, and mongo.  or fosuser and something else.

**Comment by nicolas-san** [comment]
you're right

**Comment by hackzilla** [comment]
develop branch has v4, which is almost done.
Needs a lot more documentation.

Checkout the develop branch of  [Ticket Demo App](https://github.com/hackzilla/TicketBundleDemoApp/tree/develop), as I have that working.

**Comment by nicolas-san** [comment]
I'm sorry, I don't understand what you say :)

To do this without touching the core, I have override the class in a child bundle, entity and doctrine xml files

**Comment by hackzilla** [comment]
In v4, I am completely removing entities.
I don't want to have to deal with them.

If people want extra columns, or to use UUID instead of integer, for the IDs

That said, I have some example entities for people to start with.
https://github.com/hackzilla/TicketBundle/tree/develop/Resources/doc/entities

Pretty much, everything, should be overridable.  (except for pagination).

**Comment by hackzilla** [comment]
Currently in develop branch
