### ISSUE TITLE
ROLE_TICKET_ADMIN and inheritance

### ISSUE THREAD

**Issue by Tetdoss** [hackzilla/TicketBundle#20]
Hello, I have an issue with your bundle. I have a ROLE_ADMIN as parent of ROLE_TICKET_ADMIN and even I have ROLE_ADMIN, I can't manage tickets.
I saw you are using the method hasRole to check the role, that's why it doesn't handle the inheritance.

It is written in the documentation of FOSUserBundle, next to hasRole method:

     * Never use this to check if this user has access to anything!
     *
     * Use the SecurityContext, or an implementation of AccessDecisionManager
     * instead, e.g.
     *
     *         $securityContext->isGranted('ROLE_USER');

So I guess you have to find an other way to handle it. But I have currently no idea.

Thank you

**Comment by hackzilla** [comment]
I'll have a look.

I am happy to update my code to the correct way, or a pull request is welcome

**Comment by Tetdoss** [comment]
Ok it's updated, but I have this Symfony error:

Attempted to call method "isGranted" on class "WC\UserBundle\Entity\User" in /Applications/MAMP/htdocs/Symfony/vendor/hackzilla/fosuser-bridge-bundle/User/FOSUser.php line 59.

**Comment by hackzilla** [comment]
Ah, I obviously forgot to push that fix.

I'll have to push it tonight

**Comment by hackzilla** [comment]
Commit pushed. You should be good, after another composer update.

**Comment by Tetdoss** [comment]
Ok it seems to work fine, thank you :)

But when I go to mywebsite/ticket/14/show as non-logged user I have this message:

Catchable Fatal Error: Argument 1 passed to Hackzilla\Bundle\TicketBundle\Controller\TicketController::checkUserPermission() must implement interface FOS\UserBundle\Model\UserInterface, string given, called in /Applications/MAMP/htdocs/Symfony/vendor/hackzilla/ticket-bundle/Controller/TicketController.php on line 117 and defined in /Applications/MAMP/htdocs/Symfony/vendor/hackzilla/ticket-bundle/Controller/TicketController.php line 140

But it doesn't matter because I can allow only logged user on this page.

**Comment by hackzilla** [comment]
Wouldn't have come across that, as I haven't tested when not logged in.

I'll have a look when I get a chance

**Comment by hackzilla** [comment]
I've removed the type hint, so it'll now generate 403 rather than error.

Everything is now tagged so should install normally now.

**Comment by Tetdoss** [comment]
Hello, I cannot update with the normally way (read me)

php composer.phar update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.
  Problem 1
    - hackzilla/fosuser-bridge-bundle 0.2 requires hackzilla/interfaces ~0.1 -> satisfiable by hackzilla/interfaces[0.1].
    - hackzilla/fosuser-bridge-bundle 0.2.1 requires hackzilla/interfaces ~0.1 -> satisfiable by hackzilla/interfaces[0.1].
    - hackzilla/fosuser-bridge-bundle 0.3 requires hackzilla/interfaces ~0.1 -> satisfiable by hackzilla/interfaces[0.1].
    - Conclusion: don't install hackzilla/interfaces 0.1
    - Installation request for hackzilla/fosuser-bridge-bundle ~0.2 -> satisfiable by hackzilla/fosuser-bridge-bundle[0.2, 0.2.1, 0.3].

**Comment by hackzilla** [comment]
I've just updated the readme.

Specifically you'll need:
```
        "hackzilla/fosuser-bridge-bundle": "~1.0.0",
```

**Comment by Tetdoss** [comment]
Thank you ! It's working, good job and very good bundle !
