### ISSUE TITLE
Design improvment

### ISSUE THREAD

**Issue by grimmlink** [hackzilla/TicketBundle#23]
Hello there,

i'v made some design improvements, if you are interested i can do a PR:

![image](https://cloud.githubusercontent.com/assets/3241292/6076401/59298e7c-ade3-11e4-9e54-69bd5f8f6908.png)

![image](https://cloud.githubusercontent.com/assets/3241292/6076415/7697ea08-ade3-11e4-9a48-fc43a9ca6f11.png)

![image](https://cloud.githubusercontent.com/assets/3241292/6076387/392c0d16-ade3-11e4-8a72-5edb78605a2a.png)

![image](https://cloud.githubusercontent.com/assets/3241292/6076405/64f4d1d0-ade3-11e4-9b76-cec3c984e11a.png)

**Comment by hackzilla** [comment]
I love it!

Is this all bootstrap v3?

PR is very welcome

**Comment by grimmlink** [comment]
yep bootstrap v3
inspired by github haha

**Comment by hackzilla** [comment]
Thanks for this,

Everything looks good and it has now been merged.
