### ISSUE TITLE
List of closed tickets not working in french

### ISSUE THREAD

**Issue by grimmlink** [hackzilla/TicketBundle#35]
Hi,

I have a problem on the list of closed tickets in french, it seems its not working due to the "é" character in "fermé".

Just received the notice from client so i didn't have a look at a solution yet, but i confirmed the bug by changing the translation term to "ferme" (no "é").

Will check tomorow for a fix

**Comment by grimmlink** [comment]
after further testing, it seems the "é" character is not the problem.
I also cannot reproduce the bug on my local machine, its only on the live server... makes debugging difficult.

i tracked the problem until [here](https://github.com/hackzilla/TicketBundle/blob/master/Entity/TicketMessageRepository.php#L33) where it seems the $translator doesn't have the right locale

`$translator->getLocale()` gives me `en` even though my session has `_locale => fr`

My current solution is to add `$translator->setLocale($request->getLocale());`

If anyone has a better idea ?

**Comment by hackzilla** [comment]
I'm going to create a ticket bundle demo app, with example data, to help me debug these kind of issues.

**Comment by grimmlink** [comment]
I was wondering what is the point of using the translated statuses in the url ?
would be faster and safer to use the number or at least the english version no ?

Good idea for the app!

**Comment by hackzilla** [comment]
I was going for a nicer experience.

**Comment by hackzilla** [comment]
I've have created (TicketBundleDemoApp)[https://github.com/hackzilla/TicketBundleDemoApp].
Pretty basic, but there are 5 users, each with a different locale.

In ```TicketMessageRepository``` I've dumped ```$translator->getLocale()``` and they give me the correct locale each time.

I'm tempted to add an option to use english.

**Comment by hackzilla** [comment]
Using ```$translator->setLocale($request->getLocale());``` might be masking another issue.

**Comment by grimmlink** [comment]
yes using the request language is just a temporary fix.

Did you try switching language ? My problem is it only works with the language you use when you log in. Maybe its my language switch that doesn't work well, but i only have issue with the tickets.

I'll try to get more debug done today with your bundle

**Comment by grimmlink** [comment]
Looks like the bug was on my end, my locale listener was too late to get the proper locale

**Comment by hackzilla** [comment]
Ah, that would do it.

Glad you managed to figure it out.
