### ISSUE TITLE
Add sensio/framework-extra-bundle to composer.json

### ISSUE THREAD

**Issue by edwines** [hackzilla/TicketBundle#38]
I install this bundle and expend some time trying to understand why my implementation doesn't work. The issue was that the showAction (and some others) use the sensio framework bundle `showAction(Ticket $ticket=null)`

It would be nice if the composer has this information.

Thank you for this bundle!

**Comment by hackzilla** [comment]
Thanks, I didn't notice as all my projects already had this bundle in them.
