### ISSUE TITLE
General error: 1366 Incorrect integer value: 'anon.' for column 'user_created_id' at row 1

### ISSUE THREAD

**Issue by wideawake** [hackzilla/TicketBundle#39]
As in subject. User must be logged in prior to create a ticket..

Error occurred in the demo app.

**Comment by hackzilla** [comment]
I'll have a look at this tonight.

I never expected an anon user to post a ticket, but there is no be a reason they shouldn't.

**Comment by hackzilla** [comment]
I have partially fixed this in 1.1.0

Ticket is now created, but when redirected to ticket, throws a permission denied.
This is because there is no user to validate against.

**Comment by hackzilla** [comment]
Was this a desired use case?
