### ISSUE TITLE
integrate Ticketbundle without FOSUserBundle

### ISSUE THREAD

**Issue by hakimlamaachi** [hackzilla/TicketBundle#41]
is it possible to install ticketBundle without FOSUserBundle

**Comment by hackzilla** [comment]
At the moment, it'll still install FOSUserBundle, however you can implement a new ```Hackzilla\Bundle\TicketBundle\User\UserInterface```

The FOS version is:
```Hackzilla\Bundle\TicketBundle\User\ FOSUser ```

You would be able to override it in your services.yml file.

```
parameters:
    hackzilla_ticket.user_bridge.class: Hackzilla\Bundle\TicketBundle\User\FOSUser
```

I was originally trying to build TicketBundle without tying it to any Bundles, but I needed a unique id for each user to be able to show the usernames.

Where are your users being stored?
I can try to help you integrate with that if you like.

**Comment by hakimlamaachi** [comment]
yes I create my propre Bundle ,USERBundle and classe User implement UserIterface not FOSUser , so i want to used you ticket Bundle with my class user . and thank you !!

**Comment by hackzilla** [comment]
Any chance you can show me an example?

I have [https://github.com/hackzilla/TicketBundleDemoApp] which you can fork, that I use for debugging.
A basic app with the minimum would be enough.

**Comment by hakimlamaachi** [comment]
Yes But the Demo Used FOsUserBundle So FOSUserBundle is forced

**Comment by hackzilla** [comment]
Sure, I meant reconfigure it for your use case.

It was just somewhere we could collaborate.

**Comment by hakimlamaachi** [comment]
yes but my projet is not used FosUserBundle .

**Comment by hackzilla** [comment]
I'll have think tonight, because the TicketBundle would benefit from having a method to store users, that aren't in FosUserBundle.

**Comment by hakimlamaachi** [comment]
ook thank you very  much

**Comment by hackzilla** [comment]
I am currently working on this, and hope to have something in the next couple of weeks.

My progress is in develop.

**Comment by hackzilla** [comment]
I have push develop into master.

There hasn't been any testing with anything other than FOSUserBundle.
If you can tell me what your using instead, then I can test with that before tagging v2
