### ISSUE TITLE
Minimum Symfony Version

### ISSUE THREAD

**Issue by hackzilla** [hackzilla/TicketBundle#44]
I'm looking at Symfony 3.0 (#43) compatibility.

There are some changes in Symfony 2.6, that would involve losing Symfony 2.3 compatibility.
Also in Symfony 2.8 there was a change to forms, where you have to pass Fully Qualified Class Names (FQCN) which is the way Symfony 3.0 works.

For that reason I'm considering developing for a minimum of Symfony 2.8 (previously 2.7)

Thoughts?

**Comment by grimmlink** [comment]
Hmm

I'm still using 2.7, didn't have time to adapt completely to 2.8 (which is same as 3.0)
Is there no way to keep the 2.7 ?

**Comment by hackzilla** [comment]
I have been updating my Password-Generator-Bundle, and managed to keep Symfony 2.7, so it should be the same here.

**Comment by hackzilla** [comment]
The minimum version is looking to be ```Symfony ^2.7.8```.

**Comment by hackzilla** [comment]
Now available in master
