### ISSUE TITLE
Error after closing ticket

### ISSUE THREAD

**Issue by grimmlink** [hackzilla/TicketBundle#50]
Hi,

I got this in my log after closing a ticket (and a 500 error on prod) : 

> [2016-01-26 12:39:21] request.CRITICAL: Uncaught PHP Exception Twig_Error_Runtime: "An exception has been thrown during the rendering of a template ("Catchable Fatal Error: Argument 1 passed to Symfony\Component\Form\FormRenderer::renderBlock() must be an instance of Symfony\Component\Form\FormView, null given, called in /var/www/m1/app/cache/prod/twig/fb/fb2820cadc4586d352da32dddc9c60d30e595af054396b96ea7d6e9aa87a946d.php on line 213 and defined") in "HackzillaTicketBundle:Ticket:show.html.twig" at line 78." at /var/www/m1/app/cache/prod/classes.php line 5245 {"exception":"[object] (Twig_Error_Runtime(code: 0): An exception has been thrown during the rendering of a template (\"Catchable Fatal Error: Argument 1 passed to Symfony\\Component\\Form\\FormRenderer::renderBlock() must be an instance of Symfony\\Component\\Form\\FormView, null given, called in /var/www/m1/app/cache/prod/twig/fb/fb2820cadc4586d352da32dddc9c60d30e595af054396b96ea7d6e9aa87a946d.php on line 213 and defined\") in \"HackzillaTicketBundle:Ticket:show.html.twig\" at line 78. at /var/www/m1/app/cache/prod/classes.php:5245, Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Catchable Fatal Error: Argument 1 passed to Symfony\\Component\\Form\\FormRenderer::renderBlock() must be an instance of Symfony\\Component\\Form\\FormView, null given, called in /var/www/m1/app/cache/prod/twig/fb/fb2820cadc4586d352da32dddc9c60d30e595af054396b96ea7d6e9aa87a946d.php on line 213 and defined at /var/www/m1/vendor/symfony/symfony/src/Symfony/Component/Form/FormRenderer.php:106)"} []

In dev env i get this : 
> Variable "form" does not exist in HackzillaTicketBundle:Ticket:show.html.twig at line 78

Reason is here : https://github.com/hackzilla/TicketBundle/blob/master/Controller/TicketController.php#L142

I guess adding `{% if form is defined %}` in the twig should fix it

**Comment by hackzilla** [comment]
Looking at the [template](https://github.com/hackzilla/TicketBundle/blob/master/Resources/views/Ticket/show.html.twig#L780) it looks like I've used form instead of delete_form
