### ISSUE TITLE
Question on extending entity

### ISSUE THREAD

**Issue by rdksgit** [hackzilla/TicketBundle#51]
Hi 

First of all tks for a great bundle, we are looking to implement this, however we need to add more fields and want to extend the bundle rather than making changes to the entity class provided with this bundle
Whats the best way to do this, we looked into implementing Single Table inheritance but that means we need to change the entity provided by the bundle and we really dont need to do it this way

Any suggestions?

Cheers
Sameer

**Comment by hackzilla** [comment]
Hi Sameer,

This isn't something that've thought about before, but I can see the benefit.
I'll have a think tonight.

**Comment by hackzilla** [comment]
I can see 3 ways this could be done:

- Single Table inheritance (with CompilerPass)
- Replaceable Entities (like User)
- One-to-one join

Examples of compiler pass I've found: https://github.com/mmoreram/SimpleDoctrineMapping

I'm fairly sure I don't like the "One-to-one join", but I'm not sure which of the other 2 would be the best way forward.

Unfortunately this isn't something that I've done before, but I can certainly see the benefit.

**Comment by Mangetsu** [comment]
what about a mapped super class ? like the BaseUser model from FOSUserBundle ?

**Comment by Filoz** [comment]
Hi,
This project looks very promising.

I think it would be good to have replaceable Entities (like User), it probably is the easiest way to customize an entity.

**Comment by hackzilla** [comment]
Replaceable entities with interfaces would be the most flexible.

I have just done that for the user entity.

**Comment by hackzilla** [comment]
I have pushed to develop a working implementation of replaceable entities, like FOSUserBundle.
The minimum versions are PHP 5.5, and Symfony 2.8, as I need to remove some complexity.

See readme for migration details.

Feedback welcome.

**Comment by Filoz** [comment]
Hi @hackzilla , It looks perfect!
will you merge it whith master?

To reduce the BC for anyone that installed this bundle, you can add default values of bundle confguration; something like this:
```
->defaultValue('%kernel.debug%')->end()
$treeBuilder->root('hackzilla_ticket')
            ->children()
                ->scalarNode('user_class')->isRequired()->cannotBeEmpty()->end()
                ->scalarNode('ticket_class')->isRequired()->cannotBeEmpty()->defaultValue('Hackzilla\Bundle\TicketBundle\Entity\Ticket')->end()
                ->scalarNode('message_class')->isRequired()->cannotBeEmpty()->defaultValue('Hackzilla\Bundle\TicketBundle\Entity\Message')->end()
            ->end()
        ;
```

what do you think?

**Comment by hackzilla** [comment]
Hey @Filoz, I'm happy adding that snippet.

The plan will be this will be tagged as v3, because I've bumped the minimum versions to php 5.5, and Symfony 2.8

**Comment by Filoz** [comment]
Thankyou :)
I've just send a pull request

**Comment by Filoz** [comment]
So sorry for my mistake!
Message Entity is named `TickedMessage` not  `Message`, I fixed it with a new pull request

**Comment by hackzilla** [comment]
No problem.. I missed that too.

I have pushed to master.
