### ISSUE TITLE
Why PHP 5.5 ?

### ISSUE THREAD

**Issue by charliefancelli** [hackzilla/TicketBundle#53]
Hi,

Your bundle is very interesting but i saw the new version 2.x is only for php 5.5.
Why did you lose the compatibility with php 5.3 ? The Symfony LTS (2.8.x) need php 5.3.9, i think it could be interesting to have the same requirements. 

Thanks,

**Comment by hackzilla** [comment]
2.x was about moving to Symfony 3 and I matched php requirements. 

I did take advantage of some of the php 5.5, e.g. Entity::class.

There is a possibility of rolling back the php 5.5 requirement for v2. I need to make v3 with the changes for #51

**Comment by charliefancelli** [comment]
Hi, 

Thanks, i think i could be a good thing to rolling back for the v2 and make a v3.
With this, the bundle can be compatible with the LTS version of Symfony that could be used for several years.

**Comment by hackzilla** [comment]
v2.0.1 now supports PHP 5.3
