### ISSUE TITLE
how to integrate Multilingual  translation to ticketbundle?

### ISSUE THREAD

**Issue by waliapreeti17** [hackzilla/TicketBundle#54]
I have implenmented the ticket bundle but i am not able to integrate the headings and messages as per translation.

Please repl
![translate](https://cloud.githubusercontent.com/assets/19224788/15073683/821668c8-13b8-11e6-8428-2c8c3d35ebe4.png)
y asap.

**Comment by hackzilla** [comment]
I have a working implementation you can compare with https://github.com/hackzilla/TicketBundleDemoApp

Unfortunately this is really hard for me to debug, as it could be many things.

1. Translation not enabled.

```
framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
```

2. Bundle not registered.

```
            new Hackzilla\Bundle\TicketBundle\HackzillaTicketBundle(),
```
