### ISSUE TITLE
Attachment

### ISSUE THREAD

**Issue by Filoz** [hackzilla/TicketBundle#61]
Hi @hackzilla 
a new interesting (optional) feature can be the ability to attach files to the ticket.

I found two fork of your bundle that have this feature:
https://github.com/coffee-bike/TicketBundle
https://github.com/marcelglaeser/TicketBundle

the second has also some others useful edit (configurable templates, ticket status and priority https://github.com/marcelglaeser/TicketBundle/blob/master/Entity/TicketMessage.php#L88 , ...etc..)

They refers to an old version but I think that they can be adapted easily to your current master branch

**Comment by hackzilla** [comment]
Yeah, I like it.

I can add it to v3

**Comment by hackzilla** [comment]
I've made a stab at this tonight, and will probably be able to upload it to develop in the next day or so.

**Comment by hackzilla** [comment]
I originally implemented the feature within a couple of days, but I wasn't happy with it.
I think some people will want attachments, and other won't.

So there is now TicketFeatures to enable/disable features.  At the moment its just attachment.

https://github.com/hackzilla/TicketBundle/tree/feature/file-upload

This code is a work in progress.  Assume it doesn't work.

**Comment by Filoz** [comment]
The optional feature is a perfect;
I will try it and I will give you a feedback

**Comment by hackzilla** [comment]
Cheers.. 

Things that are broken at the moment:

* Viewing attachments (need controller)
* Documentation
