### ISSUE TITLE
Errors in last dev-master

### ISSUE THREAD

**Issue by grimmlink** [hackzilla/TicketBundle#62]
Hello,

Some problems in dev-master:

`PHP Parse error:  syntax error, unexpected '[' in /vendor/hackzilla/ticket-bundle/Entity/TicketMessage.php on line 136`
https://github.com/hackzilla/TicketBundle/blob/master/Entity/TicketMessage.php#L136

`PHP Parse error:  syntax error, unexpected '[' in /vendor/hackzilla/ticket-bundle/Entity/Ticket.php at line 151 `
https://github.com/hackzilla/TicketBundle/blob/master/Entity/Ticket.php#L151

I use PHP 5.5.9

**Comment by hackzilla** [comment]
When I moved to interfaces, I couldn't use

```
    public static $statuses = array(
        self::STATUS_INVALID               => 'STATUS_INVALID',
        self::STATUS_OPEN                  => 'STATUS_OPEN',
        self::STATUS_IN_PROGRESS           => 'STATUS_IN_PROGRESS',
        self::STATUS_INFORMATION_REQUESTED => 'STATUS_INFORMATION_REQUESTED',
        self::STATUS_ON_HOLD               => 'STATUS_ON_HOLD',
        self::STATUS_RESOLVED              => 'STATUS_RESOLVED',
        self::STATUS_CLOSED                => 'STATUS_CLOSED',
    );
```

and instead I had to do
```
    const STATUSES = [
        self::STATUS_INVALID               => 'STATUS_INVALID',
        self::STATUS_OPEN                  => 'STATUS_OPEN',
        self::STATUS_IN_PROGRESS           => 'STATUS_IN_PROGRESS',
        self::STATUS_INFORMATION_REQUESTED => 'STATUS_INFORMATION_REQUESTED',
        self::STATUS_ON_HOLD               => 'STATUS_ON_HOLD',
        self::STATUS_RESOLVED              => 'STATUS_RESOLVED',
        self::STATUS_CLOSED                => 'STATUS_CLOSED',
    ];
```

The error you are seeing is PHP not supporting constant arrays, which was introduced in PHP 5.6

```
return TicketMessageInterface::STATUSES[$this->status];
```

**Comment by grimmlink** [comment]
I see, i'll have to upgrade my servers.
You should probably upgrade the PHP version in composer.json and doc so people will get a warning on updating

**Comment by hackzilla** [comment]
Cool, I'm glad that is an option for you.

I have just upgraded to PHP 7, with the latest Ubuntu LTS.

I will update the documentation/composer later today.

**Comment by hackzilla** [comment]
There are a couple of more changes I'm planning for v3, so things may change. (#63, #61)
Though I'm hopeful they won't change the bundle.

**Comment by grimmlink** [comment]
ok, it works well in php5.6 and 7.0 :+1: 
The file plugin would be awesome !

**Comment by hackzilla** [comment]
I'll close it once I've put the changes in master.  Otherwise I'm likely to forget.

**Comment by grimmlink** [comment]
haha i get it
