### ISSUE TITLE
Make Ticket / TicketMessage optional

### ISSUE THREAD

**Issue by hackzilla** [hackzilla/TicketBundle#63]
If developers choose to use Model interfaces, they are currently stuck with using having the original tables existing.

**Comment by Filoz** [comment]
To do that I think that you should revert my pull request and make the two entities abstract.
If you agree I can make a new pull request with this edit

**Comment by hackzilla** [comment]
I was thinking something like only loading them in DI if they are set in the config.

If they were abstract then no one would be able to keep using them.

**Comment by hackzilla** [comment]
To do that, I think I'll have to convert the annotations to xml

**Comment by hackzilla** [comment]
Works perfectly except for the small problem that I can't access any parameters or config when building a compiler pass.

https://github.com/hackzilla/TicketBundle/blob/feature/%2363/HackzillaTicketBundle.php

**Comment by hackzilla** [comment]
I might be able to do this by extending Doctrine's compiler pass.  I will know more tonight.

If I can't get it working, then I might scrap this feature, as people can turn off auto_mappings if they don't want my entities.

**Comment by Filoz** [comment]
You can also think to add a BC break in the v 3 branch
you make the two entities as abstract; If someone wants to use your entities has to simply extend them, like FOS User Bundle does http://symfony.com/doc/current/bundles/FOSUserBundle/index.html#step-3-create-your-user-class

**Comment by hackzilla** [comment]
Now available in develop

**Comment by Filoz** [comment]
Hi,
I saw the commit, when I have time I will try :)

I have only a doubt:
with this change, if I want to have my custom Entities I have to implement interfaces and create the mapping for every field. 
Let's think if I only need to add a field, The abstract class would give me the possibility to extend them and adding only what I need... instead with this change I have to rewrite everything, I understand it right?
I think this is less comfortable.

but anyway, great job :)

**Comment by hackzilla** [comment]
At the moment, a developer could use the existing entities untouched, or reimplement them as they see fit and implementing the interfaces.

If you want to just add a field then there is a work around, by coping the entities and adding to that.

```
app/console doctrine:mapping:convert --filter "TicketBundle" annotation src/
mkdir -p /src/AppBundle/Entity/
mv /src/Hackzilla/Bundle/TicketBundle/Entity/* /src/AppBundle/Entity/
```

Don't forget to change the namespace at the top of each entity.

```
namespace AppBundle\Entity
```

You will end up with the entities with the annotations in ```/src/AppBundle/Entity/```.
 and if you change them to ``` extends /Hackzilla/Bundle/TicketBundle/Entity/Ticket```.

That should get you the same effect as having the entities effectively abstract.

**Comment by hackzilla** [comment]
I did toy with the idea of keeping the original entities around so they could be copied, but I didn't want there to be another item to maintain.
