### ISSUE TITLE
ROLE_TICKET_ADMIN

### ISSUE THREAD

**Issue by iarenasbeyond** [hackzilla/TicketBundle#71]
I put in my security 
ROLE_ADMIN:       ROLE_TICKET_ADMIN
and the admin not show all tickets, only the admin ticket. How i can show all tickets with ROLE_ADMIN?
Thans

**Comment by hackzilla** [comment]
You don't need to add role to your security.yml file.

You only need to assign the the permission to a user.

```
app/console fos:user:promote username ROLE_TICKET_ADMIN
```

**Comment by iarenasbeyond** [comment]
I don't use FOS User Bundle, how can i do without this?

**Comment by Filoz** [comment]
You need to add that role to your user.
Your User Entity should have a method to add a Role to user (normally `addRole($role)` ). So you can create a command to promote a user (calling addRole) or a controller with a specific route...

**Comment by hackzilla** [comment]
Can you tell me what your using instead of FOS User Bundle?

I wanted to test in #47 but I have no idea what to test against.

**Comment by hackzilla** [comment]
#94 has got role_hierarchy working.
