### ISSUE TITLE
hackzilla site down

### ISSUE THREAD

**Issue by cordoval** [hackzilla/TicketBundle#74]

**Comment by hackzilla** [comment]
Thanks for letting me know.

Not sure what had happened, but its up at the moment.
Sounds like Digital Ocean had a routing problem.

**Comment by cordoval** [comment]
it is up on www.hackzilla.org but it is misleading in that it does not show a demo of the bundle, i went to use an external third party

**Comment by hackzilla** [comment]
I'm sorry it was misleading.

You can install the demo yourself with https://github.com/hackzilla/TicketBundleDemoApp
