### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by fcpauldiaz** [hackzilla/TicketBundle#76]
How I enable translations to spanish?

**Comment by hackzilla** [comment]
If you want only Spanish then in your config.yml:

```yaml
framework:
    default_locale:  "es"
```

else if you want to configure different languages then checkout my Ticket Demo:

https://github.com/hackzilla/TicketBundleDemoApp/blob/master/src/AppBundle/EventListener/UserLocaleListener.php

**Comment by fcpauldiaz** [comment]
I already have that in my config.yml. I have to do something else to make it work?

**Comment by fcpauldiaz** [comment]
I just solved it. I was missing to config the knp paginator dependency.
