### ISSUE TITLE
Configuration error

### ISSUE THREAD

**Issue by bubnovKelnik** [hackzilla/TicketBundle#90]
On fresh install of the bundle I got

Call to undefined method Symfony\Component\Config\Definition\Builder\ArrayNodeDefinition::arrayNode() in /vendor/hackzilla/ticket-bundle/DependencyInjection/Configuration.php on line 33

**Comment by hackzilla** [comment]
Can you attach your composer.lock file?

Or give me some idea of Symfony versions?

**Comment by bubnovKelnik** [comment]
Symfony 3.2

**Comment by hackzilla** [comment]
I should be able to look into this over the weekend.

**Comment by bubnovKelnik** [comment]
I have pushed the PR with fix of the Configuration.
Problem was with forgotten ->end() after booleanNode('attachment')->defaultTrue()

**Comment by bubnovKelnik** [comment]
Please merge PR #93 to develop and master due to it is a bug fix
