### ISSUE TITLE
The reserved indicator "@" cannot start a plain scalar; you need to quote the scalar

### ISSUE THREAD

**Issue by bubnovKelnik** [hackzilla/TicketBundle#91]
hackzilla_ticket.component.twig_extension.ticket_global:
        class: Hackzilla\Bundle\TicketBundle\TwigExtension\TicketGlobalExtension
        arguments:
            - @service_container
        tags:
            - { name: twig.extension }

**Comment by hackzilla** [comment]
This must be the develop branch your using?
